### ISSUE TITLE
Integrate with Docker!

### ISSUE THREAD

**Issue by gdalmau** [gdalmau/parking_manager#1]
Integrate with docker to:

- [Install the requirements](https://github.com/gdalmau/parking_manager/blob/master/README.md#installing-the-requirements)
- [Create the database](https://github.com/gdalmau/parking_manager/blob/master/README.md#installing-the-requirements)
- [Run the server](https://github.com/gdalmau/parking_manager/blob/master/README.md#installing-the-requirements)

**Comment by alirezamdv** [comment]
hi @gdalmau  I will take care of it

**Comment by gdalmau** [comment]
@alirezamdv Sure! 😄
